server:
  log_level: info

metrics:
  global:
    scrape_interval: 60s
  
  configs:
    - name: faltauno
      scrape_configs:
        - job_name: 'frontend-metrics'
          static_configs:
            - targets: ['localhost:8080']
          metrics_path: '/api/metrics'
      
      remote_write:
        - url: ${GRAFANA_PROMETHEUS_URL}
          basic_auth:
            username: ${GRAFANA_USER}
            password: ${GRAFANA_API_KEY}
